winsound.PlaySound("C:/Users/Felic/Desktop/BounceEffect.wav",
                          winsound.SND_FILENAME | winsound.SND_ASYNC)
title.write("Player: {}                                                 AI: {}       ".format(poin_player, poin_ai),
                   align="center", font=("Constantia", 24, "normal"))
                 
